import ComponentHero from './HomeComponent';
import AboutVision from './AboutVision';
import Resources from './AboutWhat';

export { default as HomeHero } from './HomeHero';
export { default as HomeMinimal } from './HomeMinimal';
export { default as HomeDarkMode } from './HomeDarkMode';
export { default as HomeLookingFor } from './HomeLookingFor';
export { default as HomeForDesigner } from './HomeForDesigner';
export { default as HomeColorPresets } from './HomeColorPresets';
export { default as HomePricingPlans } from './HomePricingPlans';
export { default as HomeAdvertisement } from './HomeAdvertisement';
export { default as HomeCleanInterfaces } from './HomeCleanInterfaces';
export { default as HomeHugePackElements } from './HomeHugePackElements';
export { default as HomeComponent } from './HomeComponent';
export { default as Impact } from './OurImpact';
export { default as Resources } from './AboutWhat';
export { default as AboutVision } from './AboutVision';
export { default as ProgramACourses } from './ProgramAndCourses';
export { default as TeachingApprach } from './TeachingApproach';
